### ISSUE TITLE
Thoughts on allowing callback for destination?

### ISSUE THREAD

**Issue by defunctl** [selective-php/transformer#1]
Just started integrating this library in a project and it's really fantastic. One thing I've run into is a need to create an unknown amount of fields that include an iterator based on the count of items in source data.

So say one source field has a count of 10 arrays, I'd want to flatten them into 10 indexed field names, but definitely a dynamic amount based on the source data, e.g.

```
'destination_0_field' => '';
'destination_1_field' => '';
'destination_2_field' => '';
etc...
```
While I could probably create a custom transformer that implements the proper interface, was curious on your thoughts on maybe solving it directly in the library as I'm sure others will have this need in the future.

Thanks!

**Comment by odan** [comment]
Hi @defunctl Thank you for your feedback. 

In my experience I never needed to do it that way and this library was not built with that feature in mind. Conceptually, the target field is always static. There is also no built-in support for dynamic targets. Even with a custom transformer, it is not possible because the transformer only handles the source rules and not the target. Perhaps this library is not the right tool for this specific purpose.

**Comment by defunctl** [comment]
Hey @odan,

Totally understandable, I'm normalizing the data after the fact now after initial mapping. I appreciate the quick response either way.
